### ISSUE TITLE
GitHub repository settings misconfigured: usdot-fhwa-stol/cdasim master branch

### ISSUE THREAD

**Issue by codygarver** [usdot-fhwa-stol/devops#112]
### Component

Infrastructure

### Specifics

- [ ] CircleCI
- [ ] Docker or Docker Hub
- [ ] Doxygen
- [ ] GitHub Actions
- [X] GitHub branch or repo
- [ ] Sonar

### What happened?

The following [usdot-fhwa-stol/cdasim settings](https://github.com/usdot-fhwa-stol/cdasim/settings) are misconfigured:
- [ ] "Do not allow bypassing the above settings" disabled!

**Comment by paulbourelly999** [comment]
Enabled "Do not allow bypassing the above settings" for branch protection rules "release" and "master"
