### ISSUE TITLE
GitHub repository settings misconfigured: usdot-fhwa-stol/carma-time-lib master branch

### ISSUE THREAD

**Issue by codygarver** [usdot-fhwa-stol/devops#118]
### Component

Infrastructure

### Specifics

- [ ] CircleCI
- [ ] Docker or Docker Hub
- [ ] Doxygen
- [ ] GitHub Actions
- [X] GitHub branch or repo
- [ ] Sonar

### What happened?

The following [usdot-fhwa-stol/carma-time-lib settings](https://github.com/usdot-fhwa-stol/carma-time-lib/settings) are misconfigured:
- [ ] "Branch protection rules" disabled!

**Comment by paulbourelly999** [comment]
Fixed by adding master branch protection rules.
