### ISSUE TITLE
GitHub repository settings misconfigured: usdot-fhwa-stol/scenario-runner develop branch

### ISSUE THREAD

**Issue by paulbourelly999** [usdot-fhwa-stol/devops#150]
### Component

Infrastructure

### Specifics

- [ ] CircleCI
- [ ] Docker or Docker Hub
- [ ] Doxygen
- [ ] GitHub Actions
- [X] GitHub branch or repo
- [ ] Sonar

### What happened?

The following [usdot-fhwa-stol/scenario-runner settings](https://github.com/usdot-fhwa-stol/scenario-runner/settings) are misconfigured:
- [ ] "Restrict who can push to matching branches" not set to Administration, Leidos Developers

**Comment by grayson-wood** [comment]
**Deviations and Issues with Aligning with carma-platform repo settings**


**Summary of current progress**
Added usdot-fhwa-stol/administration to list for "Restrict who can push to matching branches" on master, develop, and release/* branch protection rule sets.
